//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusKit.Modules.PlayerEnrichment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexusKit.Modules.PlayerEnrichment.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible right now: {0:N0}.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_active {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_button_refresh {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.button.refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_col_category {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.col.category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content ID.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_col_content_id {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.col.content_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_col_count {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.col.count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max attempts.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_col_max_attempts {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.col.max_attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_col_name {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.col.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_col_priority {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.col.priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_col_rows {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.col.rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker ETA: {0}.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_eta {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.eta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to idle.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_eta_idle {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.eta.idle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next retry: {0} (at {1:t}).
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_next_retry {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.next_retry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Queue empty.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_status_empty {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.status.empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Worker idle — next retry in {0}.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_status_idle_cooldown {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.status.idle.cooldown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Worker idle — {0:N0} rows exhausted; click Refresh on the player to retry.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_status_idle_exhausted {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.status.idle.exhausted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Worker processing — ETA {0}.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_status_processing {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.status.processing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiting for retry: {0:N0}.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_waiting {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhausted (attempt cap reached): {0:N0}.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_exhausted {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.exhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By category.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_heading_by_category {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.heading.by_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By priority.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_heading_by_priority {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.heading.by_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top characters by queue depth.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_heading_top_contents {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.heading.top_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_loading {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot of the per-character refresh queue. Drill into which content_ids are stacking up and how long until the worker has drained the backlog..
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_section_description {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.section.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh queue.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_section_nav {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.section.nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue is empty..
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_top_empty {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.top.empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total rows: {0:N0}.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_total {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unknown).
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_queuestats_unknown_name {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.queuestats.unknown_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_refresh_category_achievements {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.refresh.category.achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class jobs.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_refresh_category_classjobs {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.refresh.category.classjobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_refresh_category_gear {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.refresh.category.gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minions.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_refresh_category_minions {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.refresh.category.minions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounts.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_refresh_category_mounts {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.refresh.category.mounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_refresh_category_profile {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.refresh.category.profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled categories are never fetched — not even via the &quot;Refresh from Lodestone&quot; button. Re-enabling a category queues a catch-up fetch on the next sighting / detail selection..
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_refresh_toggles_description {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.refresh.toggles.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled categories.
        /// </summary>
        internal static string nexuskit_modules_playerenrichment_refresh_toggles_heading {
            get {
                return ResourceManager.GetString("nexuskit.modules.playerenrichment.refresh.toggles.heading", resourceCulture);
            }
        }
    }
}
